### ISSUE TITLE
please

### ISSUE THREAD

**Issue by lilongxuexi** [jkouubb/retinanet-based-on-pytorch-1.1.0#3]
你好，我想请问一下我最近想复现这个Restnanet这个算法然后对其进行改进，但是我想问一下这个主干网络在文件里面没有单独写出来，我看文档里面都是直接下载调用的，那我怎么才能动这一块呢？主干网络这一块是不能动吗？无法改进吗？麻烦了

**Comment by jkouubb** [comment]
你说的下载的模型应该指的是预训练参数。Resnet本身的代码就在resnet.py里

**Comment by lilongxuexi** [comment]
嗯嗯，懂了懂了，很感谢。可以加个微信吗博主，有些问题想请教下，有偿，麻烦了。

**Comment by lilongxuexi** [comment]
可以留个微信给我吗博主，真的很感谢，有偿

**Comment by jkouubb** [comment]
用QQ吧。。。。1014252129
以及我不一定能帮到。。。。。
